name: cache.yml

on:
  workflow_dispatch

jobs:
  test-cache:
    name: job to test cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      
      # Restore cache
      - uses: actions/cache@v4
        id: generateCache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      # Install dependencies
      - run: pip install -r requirements.txt
      
      # Verify cache usage
      - name: confirm cache 
        if: steps.generateCache.outputs.cache-hit == 'true'
        run: echo "Cache entry found"
