name: cache.yml

on:
  workflow_dispatch

jobs:
  test-cache:
    name: job to test cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/cache@v4
        id: generateCache
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-
      - run: pip install -r requirements.txt
      - name: confirm cache 
        if: steps.generateCache.output.cache-hit == 'true'
        run: echo cache entry found 
  
  
